config/routes.rb
SearchDemo::Application.routes.draw do
  resources :searches, :except => [ :update, :edit, :destroy, :show ]

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :room

  scope :by_dates_and_capacity, lambda{|start_date, end_date, adults, children| where('start_date <= ?', start_date).where('end_date >= ?', end_date).includes(:room).where('rooms.max_adult >= ?', adults).where('rooms.max_child >= ?', children)}

  def total_rate(adults, children)
    rate_adult = 10
    rate_child = 5
    charge = 20

    (rate_child * adults) + (rate_child * children) + charge
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :rates

end

app/models/search.rb
class Search < ActiveRecord::Base
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validate :date_range


  def date_range
    errors.add(:start_date, 'can not be greater than end date') if start_date > end_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :html

  def index
    @search = Search.new
  end

  def create
    @search = Search.new(params[:search])

    if @search.valid?
      @rates = Rate.by_dates_and_capacity(@search.start_date, @search.end_date, @search.max_adult, @search.max_child)
    end

    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchDemo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :max_adult %><br />
    <%= f.text_field :max_adult %>
  </div>
  <div class="field">
    <%= f.label :max_child %><br />
    <%= f.text_field :max_child %>
  </div>
  <div class="actions">
    <%= f.submit('Search') %>
  </div>
<% end %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<%= render 'form' %>

Resultados

<% if @rates %>
  <% @rates.each do | rate| %>
    <div>
      <p><%= rate.room.name %></p>
      <p><%= rate.room.max_adult + rate.room.max_child %></p>
      <p><%= rate.total_rate(@search.max_adult, @search.max_child) %></p>
    </div>
  <% end %>
<% end %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>